version: '2'

services:
  canal-server:
    image: canal/canal-server:v1.1.5
    container_name: canal-server
    ports:
      - 11111:11111
      - 11110:11110
    volumes:
      - ./canal-server/conf/:/home/admin/canal-server/conf/
    networks:
      - canal
  canal-admin:
    image: canal/canal-admin:v1.1.5
    container_name: canal-admin
    ports:
      - 8089:8089
    volumes:
    - ./canal-admin/conf/application.yml:/home/admin/canal-admin/conf/application.yml
    networks:
    - canal
networks:
  canal:
    driver: bridge
